version: '2.2'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    restart: always
    container_name: backend
    ports:
      - "8080:3000"
  # postgres:
  #   image: postgres:14
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: app
  #     POSTGRES_USER: postgres
  #   ports:
  #     - "6543:5432"
  mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        USER: mysql
        MYSQL_DATABASE: elastic
        MYSQL_USER: elastic
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
      ports:
          - "43061:3306"
      volumes:
          - ./mysql:/var/lib/mysql
  kibana:
      image: docker.elastic.co/kibana/kibana:7.9.1
      environment:
        SERVER_NAME: kibana.example.org
        ELASTICSEARCH_URL: 'http://elasticsearch:9200'
        ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
      ports:
        - 5601:5601
      restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.2'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # logstash:
  #   image: logstash:7.17.6
  #   container_name: logstash
  #   restart: always
  #   command: logstash -f /logstash_dir/logstash.conf
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./logstash/:/logstash_dir
  #   ports:
  #     - "9600:9600"